// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ2lcmj7b7yVBcWszk5ICDXHG-ST9Lhi8',
    appId: '1:461355077893:web:aaf52eb376db5091bca76c',
    messagingSenderId: '461355077893',
    projectId: 'running-laps-mario-2025',
    authDomain: 'running-laps-mario-2025.firebaseapp.com',
    storageBucket: 'running-laps-mario-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXKK7zt-4QIB8wVJ1ripcIxptj5yTG7H4',
    appId: '1:461355077893:android:ff9a05022ee4fa36bca76c',
    messagingSenderId: '461355077893',
    projectId: 'running-laps-mario-2025',
    storageBucket: 'running-laps-mario-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnc4TmGPzXkAREBAIEBRhh2S7qxvU8IMg',
    appId: '1:461355077893:ios:58b7b62266a979adbca76c',
    messagingSenderId: '461355077893',
    projectId: 'running-laps-mario-2025',
    storageBucket: 'running-laps-mario-2025.firebasestorage.app',
    iosBundleId: 'com.runninglaps.runningLaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnc4TmGPzXkAREBAIEBRhh2S7qxvU8IMg',
    appId: '1:461355077893:ios:58b7b62266a979adbca76c',
    messagingSenderId: '461355077893',
    projectId: 'running-laps-mario-2025',
    storageBucket: 'running-laps-mario-2025.firebasestorage.app',
    iosBundleId: 'com.runninglaps.runningLaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ2lcmj7b7yVBcWszk5ICDXHG-ST9Lhi8',
    appId: '1:461355077893:web:87243a46d88aa3d5bca76c',
    messagingSenderId: '461355077893',
    projectId: 'running-laps-mario-2025',
    authDomain: 'running-laps-mario-2025.firebaseapp.com',
    storageBucket: 'running-laps-mario-2025.firebasestorage.app',
  );

}